# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  MIX_ENV: test

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17.3" # [Required] Define the Elixir version
          otp-version: "27.1.3" # [Required] Define the Erlang/OTP version
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-deps-
      - name: Install dependencies
        run: mix deps.get
      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: _build
          key: ${{ runner.os }}-mix-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-build-
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Compiles without warnings
        run: mix compile --warnings-as-errors
      - name: Build assets for browser tests
        run: mix do assets.setup, assets.build
      - name: Restore JS dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-js-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-mix-js-deps-
      - name: Install JS dependencies
        run: npm ci --prefix priv/static/assets
      - name: Install chromium browser
        run: npm exec --prefix priv/static/assets playwright install chromium --with-deps --only-shell
      - name: Run tests
        run: "mix test --warnings-as-errors --max-cases 1 || if [[ $? = 2 ]]; then PLAYWRIGHT_TRACE=true mix test --max-cases 1 --failed; else false; fi"
      - name: Fail if screenshot on exit failed
        run: |
          if ! ls screenshots_for_verification/test_screenshot_3_saves_screenshot_on_test_exit* >/dev/null 2>&1; then
            echo "Screenshot on exit feature failed"
            exit 1
          fi
      - name: Upload failure traces
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Traces
          path: ./tmp
          if-no-files-found: ignore
      - name: Upload verification screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots_for_verification
          path: ./screenshots_for_verification
          if-no-files-found: ignore
